{% set name = "pyunormalize" %}
{% set version = "15.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyunormalize-{{ version }}.tar.gz
  sha256: cf4a87451a0f1cb76911aa97f432f4579e1f564a2f0c84ce488c73a73901b6c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pyunormalize
  requires:
    - pip

about:
  home: https://github.com/mlodewijck/pyunormalize
  summary: Unicode normalization forms (NFC, NFKC, NFD, NFKD). A library independent from the Python core Unicode database.
  dev_url: https://github.com/mlodewijck/pyunormalize/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
