{% set name = "pyunormalize" %}
{% set version = "18.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyunormalize-{{ version }}.tar.gz
  sha256: 2b2e65201e688bb38c66ab66ef1071cc07b32e9840e5ae07aab716db6ede7d6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyunormalize
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mlodewijck/pyunormalize
  summary: Unicode normalization forms (NFC, NFKC, NFD, NFKD). A library independent from the Python core Unicode database.
  dev_url: https://github.com/mlodewijck/pyunormalize/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
