{% set name = "pyunormalize" %}
{% set version = "16.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyunormalize-{{ version }}.tar.gz
  sha256: 2e1dfbb4a118154ae26f70710426a52a364b926c9191f764601f5a8cb12761f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pyunormalize
  requires:
    - pip

about:
  home: https://github.com/mlodewijck/pyunormalize
  summary: Unicode normalization forms (NFC, NFKC, NFD, NFKD). A library independent from the Python core Unicode database.
  dev_url: https://github.com/mlodewijck/pyunormalize/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
